version: "3.3"
services:
  mqtt:
    ports:
      - "1883:1883"
    image: "eclipse-mosquitto"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      restart_policy:
        condition: none

