#!/bin/sh
set -e
echo 'Installing python3 dependencies...'
pip3 install -r /usr/share/stoneaggregator/requirements.txt
echo 'Setting up service...'
deb-systemd-helper debian-installed stoneaggregator.service || true
deb-systemd-helper enable stoneaggregator.service || true
deb-systemd-helper update-state stoneaggregator.service
