middleware:
  beacon-max-age-seconds: 16
  report-max-age-seconds: 16
  scan-interval-seconds: 4
  mqtt-url: "tcp://localhost:1883"
  mqtt-user: ""
  mqtt-password: ""

quarkus:
  resteasy:
    path: "/api"
  native:
    resources:
      includes: "publicKey.pem"

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
    encrypt:
      key:
        location: publicKey.pem

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: "https://fieldtracks.org"
